// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5u-6s0Aspe1e4r5ArUP4A4gGa6gHJamw',
    appId: '1:420638380731:web:0b8a7cf9320b6623d80f9e',
    messagingSenderId: '420638380731',
    projectId: 'sunjob-lg-l3',
    authDomain: 'sunjob-lg-l3.firebaseapp.com',
    storageBucket: 'sunjob-lg-l3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoL2U8HZe6g-8BRJdjNpG09dKFfdGb1yo',
    appId: '1:420638380731:android:ec432da2cf238560d80f9e',
    messagingSenderId: '420638380731',
    projectId: 'sunjob-lg-l3',
    storageBucket: 'sunjob-lg-l3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1AEpjyb1Vv3qy9JXrBOZ2jPz_geTAkBI',
    appId: '1:420638380731:ios:55beecf0d3a5d96dd80f9e',
    messagingSenderId: '420638380731',
    projectId: 'sunjob-lg-l3',
    storageBucket: 'sunjob-lg-l3.firebasestorage.app',
    iosBundleId: 'com.example.dialloMamadouMalalL3glExamen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1AEpjyb1Vv3qy9JXrBOZ2jPz_geTAkBI',
    appId: '1:420638380731:ios:55beecf0d3a5d96dd80f9e',
    messagingSenderId: '420638380731',
    projectId: 'sunjob-lg-l3',
    storageBucket: 'sunjob-lg-l3.firebasestorage.app',
    iosBundleId: 'com.example.dialloMamadouMalalL3glExamen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5u-6s0Aspe1e4r5ArUP4A4gGa6gHJamw',
    appId: '1:420638380731:web:da3086dad64d761bd80f9e',
    messagingSenderId: '420638380731',
    projectId: 'sunjob-lg-l3',
    authDomain: 'sunjob-lg-l3.firebaseapp.com',
    storageBucket: 'sunjob-lg-l3.firebasestorage.app',
  );

}